name: flutter_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.1
  url_launcher: ^6.1.12
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.4
  freezed: ^2.4.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
